# Use pdfLaTeX
$pdf_mode = 1;

# Set the pdfLaTeX command line arguments
$pdflatex = 'pdflatex %O %S';

# Use Biber for bibliography
$biber = 'biber %O %B';

# Clean up additional files generated by Biber and pdfLaTeX
$clean_ext = 'bbl bcf blg log aux run.xml';

# Custom dependency and rule for running Biber
add_cus_dep('bcf', 'bbl', 0, 'runbiber');
sub runbiber {
    if (system("biber $_[0]")) {
        warn "Biber failed\n";
        return 1; # Error
    }
    return 0; # Success
}

# Specify the sequence of commands to run
$latex_sequence = ['pdflatex', 'biber', 'pdflatex', 'pdflatex'];
